

const poems = {
    0: "APPROACHING OUR END AS IT DRAWS NEAR\nSTOKING IN US THE CLEAREST FEAR.\nMEANWHILE THE SKY WILL CHURN AND YEARN,\nSPURNING ALL QUINARY EXTERNE.",
    1: "ONE QUIET AND LUMINOUS NIGHT\nWITH PERFECT GLITTERING FRAUDULENCE,\nRAYS KNIT BEAMS OF EFFULGENCE\nSHONE IN PENTAGONAL SHARDS OF LIGHT.",
    2: "GIVE EACH OF THESE MANY FEW\nTHEIR DUE BLOSSOMING TIME TOO, \nFOR THE SHORTEST OF ANY EXPRESSIONS\nLEAVE THE STRONGEST OF IMPRESSIONS.",
    3: "IN THE DEPTHS OF YOUR MIND SUSPEND\nNINE CONCENTRIC CIRCLES THAT BLEND AND REND.\nSPEND DAYS AND NIGHTS MENDING\nFROM PIECES A TRUE, PURE ENDING.",
    4: "FORTHCOMING FROM THESE AUBURN TREES\nTHE LEAVES SHUFFLE UPON THE BREEZE.\nIF THE SOUTHERN WIND IS GRACIOUS,\nPERHAPS IT HAS SUFFICIENT PATIENCE.",
    5: "STRUCK DOWN BY OUR SHRINE'S CRIME,\nTHOUGH MINE IS ANYTHING NEAR DIVINE,\nI AWAIT YOU NOW, THE PERFECT CHIME.\nAFTER MY PATIENCE, THERE ARE ONLY NINE.",
    6: "THE SUN IN RETURN WILL NOW ADJOURN\nAS THE HORIZON WILL CEASE TO BURN.\nENDEAVOR IN VAIN THE SIXTH FRONTIER,\nHERE DO WE PATIENTLY DISAPPEAR.",
}

const seasons = {
    0: "schmorplorp",
    1: "winter",
    2: "spring",
    3: "pollination",
    4: "fall",
    5: "burning",
    6: "ash",
}


const date = new Date();
const day = date.getDay();

function setSeason(){    
    var poem = document.getElementById("poem")
    var body = document.getElementById("body")

    body.setAttribute("class", "season-background " + seasons[day])

    poem.innerHTML = poems[day].replaceAll("\n", "<br />")
    
}